//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Droute.Installer.Properties {
    using System;


    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Droute.Installer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] Droute64 {
            get {
                object obj = ResourceManager.GetObject("Droute64", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;configuration&gt;
        ///    &lt;runtime&gt;
        ///        &lt;appDomainManagerType value=&quot;Droute.UpdaterHook.Bootstrapper&quot; /&gt;
        ///        &lt;appDomainManagerAssembly value=&quot;Droute.UpdaterHook, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null&quot; /&gt;
        ///    &lt;/runtime&gt;
        ///&lt;/configuration&gt;.
        /// </summary>
        internal static string UpdaterConfig {
            get {
                return ResourceManager.GetString("UpdaterConfig", resourceCulture);
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] UpdaterHook {
            get {
                object obj = ResourceManager.GetObject("UpdaterHook", resourceCulture);
                return ((byte[])(obj));
            }
        }

        /// <summary>
        ///   Поиск локализованного ресурса типа System.Byte[].
        /// </summary>
        internal static byte[] WebView2Loader {
            get {
                object obj = ResourceManager.GetObject("WebView2Loader", resourceCulture);
                return ((byte[])(obj));
            }
        }

        internal static byte[] WebView2Core {
            get {
                object obj = ResourceManager.GetObject("WebView2Core", resourceCulture);
                return ((byte[])(obj));
            }
        }

        internal static byte[] WebView2WinForms {
            get {
                object obj = ResourceManager.GetObject("WebView2WinForms", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
